name: polleriaproyecto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.7.0
  cloud_firestore: ^5.4.5
  firebase_storage: ^12.3.5
  uuid: ^4.5.1
  shared_preferences: ^2.3.3
  qr_flutter: ^4.1.0
  fl_chart: ^0.69.0
  local_auth: ^2.3.0
  provider: ^6.1.2
  font_awesome_flutter: ^10.8.0
  flutter_staggered_animations: ^1.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  pdf: ^3.11.1
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
# Aqui hay que revisar lo de las imagenes
#  assets:
#    - images/
