// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOEyo9u833JWKMmxLh0ek1ZV4rG0uMkk4',
    appId: '1:664791263673:web:77783f705bdeeafacfee68',
    messagingSenderId: '664791263673',
    projectId: 'polleria-639d8',
    authDomain: 'polleria-639d8.firebaseapp.com',
    storageBucket: 'polleria-639d8.firebasestorage.app',
    measurementId: 'G-BWELT50GFM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARhRUx-UKJ5D5uefdzkyxLo0qLWiix0sI',
    appId: '1:664791263673:android:b1c296456daa7909cfee68',
    messagingSenderId: '664791263673',
    projectId: 'polleria-639d8',
    storageBucket: 'polleria-639d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0snZuBCgxgLpp1B0QBBUAhP-Bh7gMlmo',
    appId: '1:664791263673:ios:16b520c10ef8f1e1cfee68',
    messagingSenderId: '664791263673',
    projectId: 'polleria-639d8',
    storageBucket: 'polleria-639d8.firebasestorage.app',
    iosBundleId: 'com.example.polleriaproyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0snZuBCgxgLpp1B0QBBUAhP-Bh7gMlmo',
    appId: '1:664791263673:ios:16b520c10ef8f1e1cfee68',
    messagingSenderId: '664791263673',
    projectId: 'polleria-639d8',
    storageBucket: 'polleria-639d8.firebasestorage.app',
    iosBundleId: 'com.example.polleriaproyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOEyo9u833JWKMmxLh0ek1ZV4rG0uMkk4',
    appId: '1:664791263673:web:7ea929acb02ece25cfee68',
    messagingSenderId: '664791263673',
    projectId: 'polleria-639d8',
    authDomain: 'polleria-639d8.firebaseapp.com',
    storageBucket: 'polleria-639d8.firebasestorage.app',
    measurementId: 'G-B7HMJLCTVQ',
  );
}
